module Puro
  module Http
    module Syntax
      def self.strip_line: (String) -> String

      def self.parse_h1_status: (String) -> [String, Integer]

      RE_H1_STATUS: Regexp

      def self.parse_h1_field: (String) -> [String, String]

      RE_H1_FIELD_NAME: Regexp
      RE_H1_FIELD_VALUE: Regexp

      def self.parse_h1_fields: (Enumerable[String]) { (String, String) -> void } -> void

      RE_H1_FIELD_CONT: Regexp
    end
  end
end
