module Puro
  module Http
    module H1
      class Connection
        @impl: ConnectionImpl
        @last_id: Integer

        def open_stream: -> Stream

        def close: -> void
      end
    end
  end
end
