module Puro
  module Http
    module H1
      class Stream
        attr_reader reader: BodyReader

        @io: _BufReader
        @write_state: :header | :body | :fin
        @read_state: :header | :length_delimited | :chunked | :indefinite | :fin
        @read_length: Integer
        @read_pos: Integer
        @reader: BodyReader
        @server_version: String
        @status: Integer

        def initialize: (_BufReader io) -> void

        def write_headers: (Hash[String, String] headers) -> void

        def read_headers: -> Hash[String, String]

        def readpartial_body: (Integer maxlen, String outbuf) -> String

        class BodyReader
          @stream: Stream

          def initialize: (Stream stream) -> void
          def readpartial: (Integer maxlen, ?String outbuf) -> String

          def read: -> String
        end
      end
    end
  end
end
